namespace SeattleRoasterProject.Core.Enums;

public enum SourceCountry
{
    Unknown,
    Ethiopia,
    Colombia,
    Rwanda,
    Guatemala,
    El_Salvador,
    Indonesia,
    Honduras,
    Nicaragua,
    Brazil,
    Kenya,
    Mexico,
    Costa_Rica,
    Papua_New_Guinea,
    Peru,
    Uganda,
    Burundi,
    Democratic_Republic_Of_The_Congo,
    Tanzania,
    East_Timor,
    Dominican_Republic,
    Vietnam,
    Ecuador,
    China,
    Myanmar,
    Thailand,
    Haiti,
    Yemen,
    Bolivia,
    Philippines
}